### ISSUE TITLE
Argument #1 ($host) must be of type string, null given

### ISSUE THREAD

**Issue by BlackBeltPanda** [bilan/connectlife-api-connector#30]
Attempting to run this via docker, I receive the following error: [https://pastebin.com/raw/syqdx5fw](https://pastebin.com/raw/syqdx5fw).

I'm using Compose to run the docker container and the MQTT host in this case is another docker container on the same docker network, so I'm referencing it via its container name: `http://mosquitto`. I also tried the IP of the machine, as well as "127.0.0.1", and hit the same error.

**Comment by bilan** [comment]
Paste your docker-compose file please.

**Comment by BlackBeltPanda** [comment]
> Paste your docker-compose file please.

```
services:
  ha-connectlife-addon:
    container_name: ha-connectlife-addon
    image: "ha-connectlife-addon"
    build: "https://github.com/bilan/connectlife-api-connector.git"
    command: /bin/ash -c 'php artisan app:mqtt-loop'
    environment:
      CONNECTLIFE_LOGIN: ${CONNECT_USER}
      CONNECTLIFE_PASSWORD: ${CONNECT_PASS}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASS}
      MQTT_PORT: 1883
      MQTT_SSL: false
      DEVICES_CONFIG: '{"117":{"t_work_mode":["fan only","heat","cool","dry","auto"],"t_fan_speed":{"0":"auto","5":"super low","6":"low","7":"medium","8":"high","9":"super high"},"t_swing_direction":["straight","right","both sides","swing","left"],"t_swing_angle":{"0":"swing","2":"bottom 1\/6 ","3":"bottom 2\/6","4":"bottom 3\/6","5":"top 4\/6","6":"top 5\/6","7":"top 6\/6"}}}'
    restart: unless-stopped
    networks:
      - mqtt
networks:
  mqtt:
    external: true
```
