### ISSUE TITLE
My air conditioner is not visible

### ISSUE THREAD

**Issue by prodiksun** [bilan/connectlife-api-connector#34]
I created an account using google. I started the container with ha-connectlife-addon, but I can't see my device Hisense AS-09UW4RYDDB05G. I deleted it from the application and added it again, but the problem remained.
```
root@HA:~/connectlife-api-connector# curl -v http://0.0.0.0:8000/api/devices
*   Trying 0.0.0.0:8000...
* Connected to 0.0.0.0 (127.0.0.1) port 8000 (#0)
> GET /api/devices HTTP/1.1
> Host: 0.0.0.0:8000
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Host: 0.0.0.0:8000
< Connection: close
< X-Powered-By: PHP/8.2.19
< Cache-Control: no-cache, private
< Date: Tue, 28 May 2024 09:47:27 GMT
< Content-Type: application/json
< 
* Closing connection 0
```

**Comment by bilan** [comment]
Try creating account by e-mail, not google or other social account.

**Comment by prodiksun** [comment]
Surprisingly, on the website https://oauth.hijuconn.com / writes that such a login does not exist.
![Снимок экрана 2024-05-28 132234](https://github.com/bilan/connectlife-api-connector/assets/47965173/eacb6358-0b57-44aa-afec-eb1a387bcf2d)

**Comment by bilan** [comment]
The problem is in your region I think, check out this thread:
https://github.com/bilan/connectlife-api-connector/issues/25

**Comment by prodiksun** [comment]
> The problem is in your region I think, check out this thread: #25

Yes, I read it, as a result, I made the traffic flow through the VPN.

**Comment by prodiksun** [comment]
But Russia is defined in the application, but I don't know how to change it.

**Comment by bilan** [comment]
iOS app asked me about location on account creation process or first login (didn't remember).

**Comment by prodiksun** [comment]
Yes, it helped, but you can do it on android, if you do not click that a citizen of Russia is offered a choice of country.

**Comment by prodiksun** [comment]
Thank you very much, everything worked out!
![Снимок экрана 2024-05-28 145141](https://github.com/bilan/connectlife-api-connector/assets/47965173/860fa5d5-9daf-4166-9e75-1bbd95679372)

**Comment by Monacoslo** [comment]
> Yes, it helped, but you can do it on android, if you do not click that a citizen of Russia is offered a choice of country.

Unfortunatelly this is due Russian legislation about data storage. But in the future I am affraid even that will not work anymore due the EU sanctions against Russia. Stupid political games...

**Comment by capretto78** [comment]
> Thank you very much, everything worked out! ![Снимок экрана 2024-05-28 145141](https://private-user-images.githubusercontent.com/47965173/334399387-860fa5d5-9daf-4166-9e75-1bbd95679372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTA0MzcsIm5iZiI6MTcxODA5MDEzNywicGF0aCI6Ii80Nzk2NTE3My8zMzQzOTkzODctODYwZmE1ZDUtOWRhZi00MTY2LTllNzUtMWJiZDk1Njc5MzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA3MTUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NzI0YzNlMTRiNTY3MzBkNjAwMjljZmQ3MTBjMjM4MWM3NGEyZmU2ZjY2YjkwZTQ3ZDAyZDllNjcxMzQ5ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9BT0J6--HKlCRqfKXAX0TJ37HzeNE-Wjq89grM7zpq0)

How did you manage to get this view of your air conditioner? I installed the component and detected the entity related to my air conditioner, but I can't get your view.

**Comment by prodiksun** [comment]
> > Thank you very much, everything worked out! ![Снимок экрана 2024-05-28 145141](https://private-user-images.githubusercontent.com/47965173/334399387-860fa5d5-9daf-4166-9e75-1bbd95679372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTA0MzcsIm5iZiI6MTcxODA5MDEzNywicGF0aCI6Ii80Nzk2NTE3My8zMzQzOTkzODctODYwZmE1ZDUtOWRhZi00MTY2LTllNzUtMWJiZDk1Njc5MzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA3MTUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NzI0YzNlMTRiNTY3MzBkNjAwMjljZmQ3MTBjMjM4MWM3NGEyZmU2ZjY2YjkwZTQ3ZDAyZDllNjcxMzQ5ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9BT0J6--HKlCRqfKXAX0TJ37HzeNE-Wjq89grM7zpq0)
> 
> How did you manage to get this view of your air conditioner? I installed the component and detected the entity related to my air conditioner, but I can't get your view.

![Uploading Снимок экрана 2024-06-11 103727.png…]()

**Comment by prodiksun** [comment]
```

**Comment by prodiksun** [comment]
@capretto78
```
version: '3.8'

services:
  ha-connectlife-addon:
    image: ha-connectlife-addon
    container_name: ha-connectlife-addon
    restart: always
    ports:
      - 8000:8000
    environment:
      - CONNECTLIFE_LOGIN=mail@mail.ru
      - CONNECTLIFE_PASSWORD=mail_pass
      - LOG_LEVEL=info
      - MQTT_HOST=192.168.88.200
      - MQTT_USER=homeassistant
      - MQTT_PASSWORD=passmqtt
      - MQTT_PORT=1883
      - MQTT_SSL=false
#      - DEVICES_CONFIG='{"117":{"t_work_mode":["fan only","heat","cool","dry","auto"],"t_fan_speed":{"0":"auto","5":"super low","6":"low","7":"medium","8":"high","9":"super high"},"t_swing_direction":["straight","right","both sides","swing","left"],"t_swing_angle":{"0":"swing","2":"bottom 1\/6 ","3":"bottom 2\/6","4">
    command: /bin/ash -c '/usr/bin/supervisord -c /home/app/docker-files/supervisord.conf'
```
