### ISSUE TITLE
Unable to start service base-addon-banner

### ISSUE THREAD

**Issue by adam3278** [bilan/connectlife-api-connector#53]
Hello,
I cannot get the service up due to error. I tried putting all the configuration options or changing formatting of provided ones, but it doesn't help. If you can, I would really appreciate small help.
```log
mqtt-hisense_1  | s6-rc: info: service s6rc-oneshot-runner: starting
mqtt-hisense_1  | s6-rc: info: service s6rc-oneshot-runner successfully started
mqtt-hisense_1  | s6-rc: info: service base-addon-banner: starting
mqtt-hisense_1  | /usr/lib/bashio/log.sh: line 107: info: unbound variable
mqtt-hisense_1  | s6-rc: warning: unable to start service base-addon-banner: command exited 1
mqtt-hisense_1  | /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
mqtt-hisense_1  | /run/s6/basedir/scripts/rc.init: fatal: stopping the container.
mqtt-hisense_1  | s6-rc: info: service s6rc-oneshot-runner: stopping
mqtt-hisense_1  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

This is my docker compose:
```yaml
mqtt-hisense:
    build: "https://github.com/bilan/connectlife-api-connector.git"
    restart: unless-stopped
    environment:
     DISABLE_HTTP_API: 'true'
     CONNECTLIFE_LOGIN: 'xxxx'
     CONNECTLIFE_PASSWORD: 'xxxx'
     LOG_LEVEL: info
     MQTT_HOST: 'mqtt-hisense'
     MQTT_USER: mqtt
     MQTT_PASSWORD: 'mqtt-pass'
     MQTT_PORT: '1883'
     MQTT_SSL: 'false'
     DEVICES_CONFIG: '{"117":{"t_work_mode":["fan only","heat","cool","dry","auto"],"t_fan_speed":{"0":"auto","5":"super low","6":"low","7":"medium","8":"high","9":"super high"},"t_swing_direction":["straight","right","both sides","swing","left"],"t_swing_angle":{"0":"swing","2":"bottom 1\/6 ","3":"bottom 2\/6","4":"bottom 3\/6","5":"top 4\/6","6":"top 5\/6","7":"top 6\/6"}}}'
    command: "/bin/ash -c 'php artisan app:mqtt-loop'"
```
